scikit-hep/fastjet

.github/workflows/ci.yml, .github/workflows/wheels.yml, .gitignore, README.md
Resolves #55 
**Suggested squash and merge commit message**:
```
* Update build-time dependencies for Debian based operating systems
- Add: gfortran swig autoconf libtool
- Note that these are for Debian/Ubuntu
* Update build-time dependencies in CI to match those in docs
* Advocate for using `python -m pip` in all uses of `pip`
* Add CGAL to .gitignore
```
=> docs: Update build-time dependencies for Debian/Ubuntu

setup.py
https://gitlab.com/fastjet/fastjet/-/blob/fastjet-3.3.4/INSTALL#L55-60
Critically it is necessary to remove this line for builds to work on centos7.
It does not affect building on debian-likes.
=> remove --enable-cgal for rc6, re-enable in rc7

.github/workflows/ci.yml, .github/workflows/wheels.yml, README.md, pyproject.toml, setup.py, src/fastjet/__init__.py, src/fastjet/version.py
Summary of this PR:
* All ldd "Not Found" errors were resolved by linking with `-rpath=$ORIGIN/_fastjet_core/lib`, with sufficient quoting on the "`$ORIGIN`". Different parts of the configure/make procedure evaluate it at different levels, so just protecting the `$` is not enough: I had to define an environment variable so that `$ORIGIN` would resolve to "`$ORIGIN`".
* Dropped PxCone because libgfortran is not found. According to @lgray, "PxCone is from 2006 and was most recently cited in a Herwig benchmarking paper for completeness in 2016." It's probably safe to ignore PxCone.
* Intermediate commits were attempts to get it to work on MacOS. [Last attempt in ci.yml](https://github.com/scikit-hep/fastjet/actions/runs/1137341103), and [last attempt in …
=> Add $ORIGIN/_fastjet_core/lib to RPATH for PyPI wheels.

.pre-commit-config.yaml, pyproject.toml, setup.cfg, src/fastjet/_pyjet.py, tests/test_003-vector.py
Committed via https://github.com/asottile/all-repos
=> chore: wheel not required for setuptools PEP 517 (all-repos)

.github/dependabot.yml
This is now supported, updates match the original number of version digits.
=> ci: update official actions

src/fastjet/__init__.py
This PR adds return type annotations to the ClusterSequence class, allowing code analysis tools such as pylance to understand fastjet methods. The previous behavior was that pylance read the abstract method definitions and concluded that the methods allows raised an error. This marked all code after a fastjet call as unreachable.
=> Add type annotations to ClusterSequence

MANIFEST.in, patch.sed, patch.txt, setup.py, src/fastjet/version.py
This PR is introducing FastJet core version 3.4.0 (the latest stable out). As I have described in the comments in PR #68, the introduction of `FastJetError` makes the swig-generated code not importable for us. Therefore a patch is needed for the moment in the swig description file. I am using sed to apply the patch but I am open to other better approaches. I have already opened an [upstream merge request](https://gitlab.com/fastjet/fastjet/-/merge_requests/1) that would solve this in a better way. I am not sure when and if this will get merged, but once it does then we can remove the patch. I would also like to make a new release soon (I believe that would be 3.4.0.0rc1) because I need to get some of the recent updates to my work areas. Are there any objections to this?
=> Bump FastJet version to 3.4.0 from 3.3.4 using a patch

.clang-format, .pre-commit-config.yaml, MANIFEST.in, src/_ext.cpp
`clang-format` in pre-commit for C++ files (only `src/_ext.cpp` for us).
=> Introduce clang-format in pre-commit

README.md
More libraries are now required because of CGAL.
Fixes #138
=> Update README.md Debian install requirements

src/_ext.cpp, src/fastjet/__init__.py, src/fastjet/_generalevent.py, src/fastjet/_multievent.py, src/fastjet/_pyjet.py, src/fastjet/_singleevent.py, tests/test_002-exclusive_jets.py
Adding the `exclusive_jets_constituent_index` and `exclusive_jets_constituents` (for a specified number of jets) functions, which retrieve particle constituents of exclusive jets similar to the `constituents` and `constituent_index` functions.
This partially solves #100, but future PRs may want to add the `dcut` arg and implementations for exclusive *subjets* as well.
=> Exclusive jet constituents

.gitmodules, MANIFEST.in, setup.py, src/_ext.cpp
This approach adds some overhead (compiling all of `fastjet-contrib`), but in principle allows us to add helper functions to use other contributions like SoftDrop, Nsubjettiness, EnergyCorrelationFunctions, etc.
=> fj-contrib

setup.cfg, src/fastjet/_generalevent.py, src/fastjet/_multievent.py, src/fastjet/_pyjet.py, src/fastjet/_singleevent.py, tests/test_002-exclusive_jets.py, tests/test_007-general.py
I wasn't able to test locally. I _think_ I got all the right changes. Let's see what CI thinks.
=> fix: update codebase to Awkward 2.0.0.

.github/workflows/ci.yml, .github/workflows/wheels.yml, src/fastjet/__init__.py
Swig 4.1.X changed the way it handles functions with `@staticmethod`. Up to version 4.0.2 it used to produce an additional flat-named function for each static method. For example, the function `ClusterSequence.fastjet_banner_stream()` used to also have a flat-name counterpart: `ClusterSequence_fastjet_banner_stream()`. Now, this is gone. 
More info here https://github.com/swig/swig/pull/2137
I just removed those imports. Tests seem to be fine and I couldn't find any uses for them.
=> Fix for swig 4.1.X

src/fastjet/version.py
Anything else we want to include before publishing v3.4.0.3?
It'd be nice to get this out so we can `pip install fastjet` on macOS! 😃
=> update to v3.4.0.3

.github/workflows/ci.yml, .github/workflows/wheels.yml, tests/test_002-exclusive_jets.py
Addresses #165.
Building `aarch64` wheels with QEMU does indeed take a while (~1 hour 30 min) as noted by @lgray, so a self-hosted runner or separate CI would be better long term.
<s>Also @rkansal47, there is a minor numerical difference for the Lund clustering that required changing the test from checking for equality to closeness. Interestingly, this is the only test that requires this. You can see the numerical difference in the first failing CI check. I presume this is ok, but do you have any thoughts about why it happens here?</s> I agree with @henryiii that we should probably be using `ak.isclose()` with an appropriate tolerance for all tests anyway.
=> Test `aarch64` wheels

.cirrus.yml, .github/workflows/ci.yml, MANIFEST.in, README.md
* Follow up PR to PR #166 
* Add Cirrus CI config for aarch64 wheel tests.
* Exclude .cirrus.yml from MANIFEST.in.
* Remove QEMU based config for time.
* Add Cirrus CI badge to README.
- [![cirrus-ci Status][cirrus-ci-badge]][cirrus-ci-link]
[cirrus-ci-badge]:          https://api.cirrus-ci.com/github/scikit-hep/fastjet.svg?branch=main
[cirrus-ci-link]:           https://cirrus-ci.com/github/scikit-hep/fastjet
```
* Add Cirrus CI config for aarch64 wheel tests.
- The jobs take a large amount of memory and so modification
of the default resources is needed.
* Exclude .cirrus.yml from MANIFEST.in.
* Remove GitHub Actions QUEM based aarch64 test. As the Cirrus CI takes minutes
instead of over an hour there is now not a need for this test to run in
GitHub Actions.
* Add Cirrus CI build status …
```
=> ci: Add Cirrus CI config for aarch64 build tests

setup.py
Turn on thread safety options so users don't run into nasty surprises using dask.
=> enable thread safety by default in fastjet

.pre-commit-config.yaml, src/_ext.cpp, src/fastjet/__init__.py, src/fastjet/_generalevent.py, src/fastjet/_multievent.py, src/fastjet/_pyjet.py, src/fastjet/_singleevent.py, tests/test_002-exclusive_jets.py
Hello,
I have implemented `exclusive_jets_energy_correlator` to calculate the ECFs and ECFGs of a fatjet, as well as the included combinations (i.e. N2, D2, and so on). 
An important note: I have made the generalized ECF (ECFG) the default case, because the generic ECF does not include baked in normalization, which I suspect most users would expect out of the gate. That said, the combinations will probably be used more often than the the basic ECF, especially NSeries and D2.
=> feat: Adding EnergyCorrelator from Contrib

tests/test_008-dask.py
Cirrus CI is having issues with accessing the sample file over `https` for the python 3.11 jobs. 
I switched to use the local file from the cloned repository.
=> ci: Use file from cloned repo instead of https access

src/_ext.cpp
Noticed some warnings in the compilation log coming from `_ext.cpp`. I removed 4 lines that were giving warnings about unused variables.
=> chore: Remove unused variables

.github/workflows/ci.yml, .github/workflows/wheels.yml
upload-artifact v4 cannot overwrite artifacts and this causes the tests to fail.
=> ci: fix failing tests after update to upload-artifact v4

src/fastjet/version.py
Bump FastJet to v3.4.2.
[Edit]
FastJet v3.4.2 looks okay. Will update pybind11 too to v2.11.1.
=> chore: Bump FastJet to v3.4.2 and pybind11 to v2.11.1

setup.py
Requires PR #276 to go in first. (Splitting these to keep the commits atomic)
Use of `$$` for the parameter expansion of `ORIGIN` results in a failure to properly resolve `$ORIGIN` and for `LDFLAGS` to be set improperly. Use `$ORIGIN` instead.
c.f. https://github.com/lgray/staged-recipes/pull/3 for this patch being required for a build to succeed for https://github.com/conda-forge/staged-recipes/pull/21052.
The use of `$$` was added by @jpivarski in PR https://github.com/scikit-hep/fastjet/pull/65, so maybe he can elaborate on the need there and if this PR is missing something. A quick scan of the PR makes it seem like
>  Different parts of the configure/make procedure evaluate it at different levels, so just protecting the `$` is not enough: I had to define an environment variable so …
=> fix: Update RPATH and fully guard ORIGIN parameter expansion

MANIFEST.in
Amends PR #206 
`patch_fastjet_i.txt` was removed in PR #206 and so should be removed from the MANIFEST to avoid warnings.
=> fix: Remove patch_fastjet_i.txt from MANIFEST.in

.cirrus.yml, .github/workflows/ci.yml, .github/workflows/wheels.yml
* Update the CI to also test Python 3.12 and use it as a default in situations where only one version is tested.
=> ci: Add Python 3.12 to testing matrix

.github/workflows/ci.yml, .github/workflows/wheels.yml
Committed via https://github.com/asottile/all-repos
=> ci: macos-latest is changing to macos-14 ARM runners

setup.py
* Addresses part of Issue #279 
* Addresses part of Discussion #302
While doing multiple rebuilds it is advisable to also clean up the state of the Git submodules with `git clean -f`, removing the `OUTPUT` directory at `src/fastjet/_fastjet_core/` and the top level build directory is sufficient to do local development rebuilds &mdash; i.e., the command `python -m pip install --upgrade .` can be run twice in a row without error.
=> build: Remove transient directories after install to allow for rebuild

.gitmodules, MANIFEST.in, setup.py
Move the https://gitlab.com/fastjet/fastjet.git and https://github.com/cms-externals/fastjet-contrib.git Git submodules into an 'extern' directory to make the directory management cleaner.
This implements a comment from @henryiii back in https://github.com/scikit-hep/fastjet/pull/1#issuecomment-820682557.
This does not move the `pybind11` submodule given PR #313 removes it.
=> build: Move Git submodules to extern directory

.github/workflows/ci.yml, .gitmodules, MANIFEST.in, pyproject.toml
Resolves #309 
* Update lower bound on build-system pybind11 to v2.12.0 to add support for compiling for NumPy 2.0.
- c.f. https://github.com/pybind/pybind11/releases/tag/v2.12.0
* Remove pybind11 submodule to use build-system instead.
* Add an easy to parse log of the environment used for each test, which is useful for debugging differences between CI jobs seperated in time.
For reference, the `pybind11` Git submodule was added in https://github.com/scikit-hep/fastjet/commit/0f9f8fff63761aa63a50471f22880b579b1e6ff2 by @jpivarski, though as this wasn't part of a PR I'm not sure why the Git submodule approach was used over [the other `pybind11` install methods](https://pybind11.readthedocs.io/en/stable/installing.html).
=> build: Use build-system pybind11 over Git submodule

CMakeLists.txt
- applies and improves a patch from conda-forge that allows a passthru-patch to the system-installed fastjet swig module
- NB: it must have a different name from `fastjet`, anyone doing this manually will likely know how to do that (and fastjet has corresponding options)
- allow user to set the system fastjet swig module name in the passthru import
- add an option for copying the gmp dll on windows
=> build: add more build options; obviates fastjet-feedstock patch for passthru submodule
