scikit-hep/fastjet

setup.py
Pulling out just the cleanup from #4.
=> chore: cleanup setup.py structure a bit

.github/workflows/wheels.yml, README.md
I'm not sure if this will work as-is, but it's the beginning of a pull request to try to get it to work.
=> Attempt to build the SDist after making it.

README.md
=> docs: Use --recursive alias to --recurse-submodules

pyproject.toml, tests/test_003-vector.py, tests/test_005_sorting.py
Temporary fix to get the CI working again.
=> fix: limit setuptools for now

.github/workflows/ci.yml, .github/workflows/wheels.yml
cannot use fastjet with cpython 3.10
=> build wheels for all cpython versions

tests/test_003-vector.py, tests/test_005_sorting.py
Bump pybind11 from v2.6.2 to v2.10.0
=> Bump pybind11 from v2.6.2 to v2.10.0

src/fastjet/version.py
=> Fastjet is v3.4.0.0

src/fastjet/version.py
- update to v3.4.0.2; the major change is compatibility with awkward 2.0.0 (the previous version is incompatible and will break)
=> update to v3.4.0.2

README.md
- Update README.md to get logo on PyPI
=> Update README.md to get logo on PyPI

src/fastjet/version.py
=> bump version to 3.4.0.4

src/fastjet/_generalevent.py, src/fastjet/_multievent.py, src/fastjet/_singleevent.py, src/fastjet/version.py
=> Bump to 3.4.0.5

MANIFEST.in, patch_makefilein.txt, setup.py
=> Patch out the override of CXX and CXXFLAGS in fastjet-contrib/Makefile.in

tests/test_008-dask.py
Just pointing the url for the dask tests to main instead of some random commit hash.
=> Update url for test file

setup.cfg
Flip across the boundary for dask 2023.4.0 for dask_awkward.
=> chore: repin dask, dask-awkward

src/fastjet/_pyjet.py
cf. https://github.com/scikit-hep/awkward/pull/2437
=> fix: account for deprecation of highlevel length_zero_array

src/_ext.cpp, src/fastjet/_generalevent.py, src/fastjet/_multievent.py, src/fastjet/_pyjet.py, src/fastjet/_singleevent.py, tests/test_002-exclusive_jets.py
=> feat: Add exclusive_jets_up_to() interface

setup.cfg
=> fix: add dask-awkward[test] as dependency

.github/workflows/ci.yml, .github/workflows/pr.yml, .github/workflows/wheels.yml
Following Henry's suggestion to reduce updates https://github.com/scikit-hep/fastjet/pull/252#issuecomment-1734198811.
=> ci: Pin on two digits

.github/workflows/wheels.yml
=> ci: fix pypi publish

src/fastjet/version.py
=> chore: bump version to 3.4.2.1

.github/workflows/ci.yml, .github/workflows/wheels.yml, setup.cfg, setup.py
=> ci: get macos builds running again

src/fastjet/version.py
=> fastjet is v3.4.3.0rc0

.github/workflows/ci.yml, .github/workflows/wheels.yml, setup.py
Let's see if we can get universal2 builds working?
=> build: macos x86_64 wheels using macos-13 runner

src/fastjet/version.py
=> chore: fastjet is now v3.4.3.0

pyproject.toml
=> fix: PyPI info

pyproject.toml
=> build: switch to default cibw build image for linux (manylinux_2_28)

pyproject.toml
latest awkward should be compatible
=> build: unpin numpy 2.3
